In [26]:
# I am done understanding the code and logics of this file.

In [27]:
# Just Testing the speed of arrays of numpy vs python lists

import numpy as np
import time
# Python list
py_list = list(range(1000000))
# NumPy array
np_array = np.arange(1000000)
# Multiply each element by 2- Python way
start = time.time()
py_result = [x * 2 for x in py_list]
py_time = time.time()- start
# Multiply each element by 2- NumPy way
start = time.time()
np_result = np_array * 2 # Vectorized operation!
np_time = time.time()- start
print(f"Python list time: {py_time:.4f} seconds")
print(f"NumPy array time: {np_time:.4f} seconds")
print(f"NumPy is {py_time/np_time:.1f}x faster!")

Python list time: 0.2430 seconds
NumPy array time: 0.0058 seconds
NumPy is 41.8x faster!


In [28]:
# Just creating some arrays in different ways

# From list
arr1 = np.array([1, 2, 3, 4, 5])
print(f"from list: {arr1}")
# From list of lists (2D array)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"from list of lists: {arr2}")
# Zeros and ones
zeros = np.zeros((3, 4)) # 3 rows, 4 columns
ones = np.ones((2, 3))
print(f"zeros: {zeros}")
print(f"ones: {ones}")
# Range
range_arr = np.arange(0, 10, 2) # Start, stop, step: [0, 2, 4, 6, 8]
print(f"range: {range_arr}")
# Linear space
linspace_arr = np.linspace(0, 1, 5) # 5 points from 0 to 1: [0, 0.25, 0.5, 0.75, 1]
print(f"linear space: {linspace_arr}")
# Random
random_arr = np.random.rand(3, 3) # Uniform [0, 1)
normal_arr = np.random.randn(1000) # Standard normal
print(f"random: {random_arr}")
print(f"normal: {normal_arr}")
# Identity matrix
identity = np.eye(4)
print(f"identity: {identity}")

from list: [1 2 3 4 5]
from list of lists: [[1 2 3]
 [4 5 6]]
zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]
range: [0 2 4 6 8]
linear space: [0.   0.25 0.5  0.75 1.  ]
random: [[0.41652247 0.94432298 0.17797781]
 [0.87714414 0.7079411  0.44853952]
 [0.45971857 0.00654474 0.84996788]]
normal: [-2.15432406e+00 -6.11680796e-01 -1.04863957e+00  1.11495052e-01
 -1.37037862e-02  2.31009452e+00 -1.55277935e-01  1.62078991e+00
 -5.45421413e-01  5.75460405e-01 -5.47658397e-01  2.54048940e+00
  6.44941392e-01  2.67516104e-01 -1.26186243e+00 -2.66915044e-02
  7.94729184e-01 -7.72645536e-01 -5.71199743e-01  6.55235590e-01
  3.98100577e-01 -3.47309402e-01  1.37256931e+00 -1.37039033e+00
 -5.45326130e-01  7.69921249e-01  8.73495574e-01  2.18624950e+00
 -1.56707537e+00  1.21138725e-01  2.20090979e-01  2.37287832e-01
 -5.39698825e-01 -6.05344067e-01 -3.59947216e-01  4.17989616e-01
 -1.41220643e+00  6.51603249e-01 -1.23705754e+00 -5.41397368e-01
  9.44780039e-01  1

In [29]:
# Exploring attributes(shape, size, dtype, etc.) of NumPy arrays

arr = np.random.rand(3, 4)
print(f"Shape: {arr.shape}")
# (3, 4)
print(f"Dimensions: {arr.ndim}") # 2
print(f"Size (total elements): {arr.size}") # 12
print(f"Data type: {arr.dtype}")
# float64
print(f"Item size (bytes): {arr.itemsize}") # 8
print(f"Total bytes: {arr.nbytes}") # 96


Shape: (3, 4)
Dimensions: 2
Size (total elements): 12
Data type: float64
Item size (bytes): 8
Total bytes: 96


In [30]:
# Indexing and slicing of NumPy arrays

arr = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
print(arr)
# Basic indexing
element = arr[1, 2] # Row 1, Column 2 → 7
print(element)
# Slicing
row = arr[0, :]
col = arr[:, 1]
print(row)
print(col)
# First row: [1, 2, 3, 4]
# Second column: [2, 6, 10]
submatrix = arr[0:2, 1:3] # Rows 0-1, Columns 1-2 → [[2, 3], [6, 7]]
# Boolean indexing
mask = arr > 5
values_gt_5 = arr[mask] # [6, 7, 8, 9, 10, 11, 12]
# Fancy indexing (integer arrays)
indices = arr[[0, 2], [1, 3]] # arr[0,1] and arr[2,3] → [2, 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[1 2 3 4]
[ 2  6 10]


In [31]:
# Element-wise operations and aggregations

a = np.array([1, 2, 3])
b =np.array([4, 5, 6])
# Element-wise operations
print(a + b)
print(a * b)
# [5, 7, 9]
# [4, 10, 18]
print(a ** 2) # [1, 4, 9]
print(np.sqrt(a)) # [1, 1.414, 1.732]
# Linear algebra
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([5, 6])
product = matrix @ vector # Matrix multiplication
# Or: np.dot(matrix, vector)
# Aggregations
arr = np.random.randn(100)
print(f"Mean: {arr.mean():.3f}")
print(f"Std: {arr.std():.3f}")
print(f"Min: {arr.min():.3f}")
print(f"Max: {arr.max():.3f}")
print(f"Sum: {arr.sum():.3f}")
# Axis operations (for 2D arrays)
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
row_sums = arr_2d.sum(axis=1) # Sum each row: [6, 15, 24]
col_sums = arr_2d.sum(axis=0) # Sum each column: [12, 15, 18]

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
Mean: -0.101
Std: 1.037
Min: -3.284
Max: 3.618
Sum: -10.144


In [32]:
# Reshaping, flattening, transposing, and adding dimensions

arr = np.arange(12)
print(f"original: {arr}")
# Reshape
reshaped = arr.reshape(3, 4) # 3 rows, 4 columns
print(f"after reshaping: {reshaped}")
# [[0, 1, 2, 3],
# [4, 5, 6, 7],
# [8, 9, 10, 11]]
# Flatten
flattened = reshaped.flatten() # Back to 1D
print(f"after flattening: {flattened}")
# Transpose
transposed = reshaped.T # Swap rows and columns
print(f"after transposing: {transposed}")
# [[0, 4, 8],
# [1, 5, 9],
# [2, 6, 10],
# [3, 7, 11]]
# Add new dimension
row_vector = arr[np.newaxis, :] # Shape (1, 12)
col_vector = arr[:, np.newaxis] # Shape (12, 1)
print(f"row vector: {row_vector}")
print(f"column vector: {col_vector}")

original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
after reshaping: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
after flattening: [ 0  1  2  3  4  5  6  7  8  9 10 11]
after transposing: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
row vector: [[ 0  1  2  3  4  5  6  7  8  9 10 11]]
column vector: [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
